apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordcounter-frontend
  labels:
    app: wordcounter 
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wordcounter 
      tier: frontend
  template:
    metadata:
      labels:
        app: wordcounter 
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: wordcounter-frontend
        ports:
        - name: http-server
          containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name:  BACKEND_API_ADDR
          value: wordcounter-backend:8080
