apiVersion: v1
kind: Service
metadata:
  name: wordcounter-backend
  labels:
    app: wordcounter
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: wordcounter
    tier: backend
  ports:
  - port: 8080
    targetPort: http-server
