apiVersion: skaffold/v1beta15
kind: Config
build:
  artifacts:
  - image: wordcounter-backend
    context: src/backend
  - image: wordcounter-frontend
    context: src/frontend
  tagPolicy:
    sha256: {}
deploy:
  kubectl:
    manifests:
    - ./kubernetes-manifests/*.service.yaml
    - ./kubernetes-manifests/*.deployment.yaml
profiles:
- name: cloudbuild
  build:
    googleCloudBuild: {}

